server:
  port: 9005

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/eba_db
    username: enviro_ba_user
    password: localpasswd
account-constants:
  minimum: 1000.00
  overdraft: 10000.00
